### ISSUE TITLE
Recommendations to wrap all calls to Rails.cache

### ISSUE THREAD

**Issue by senny** [ParentSquare/faulty#13]
This is not in issue but rather a question. If GitHub tickets are not the place to post questions, please feel free to redirect me to a different spot.

I am looking for a circuit breaker implementation for our app and was comparing the APIs of Faulty and Semian. Our product unfortunately has a massive amount of integration points and the custom circuit API from faulty does suit this part rather well. What I was wondering though, is how I could efficiently protect against issues with key dependencies like our Redis cache or the follower database. Is the recommended approach with Faulty that we would need to wrap each call to `Rails.cache` with the circuit? How would we catch calls made from framework components and the like?

Thanks for your time and effort on the gem! Great job on the documentation, found answers to pretty much all my questions.

**Comment by justinhoward** [comment]
Great question. If you're familiar with Semian, you know that it has "adapters", which are monkey-patches for various common network services. Semian also provides `Semian::Adapter` for creating your own adapters if you prefer. Faulty doesn't provide anything like that, and all circuits have to be manually applied.

So far, for ParentSquare's use-cases, we prefer this custom one-off implementation. We're not yet using it for core services like cache or databases. So short answer is that you'd currently need to wrap each call to `Rails.cache` or your database. Obviously this is not ideal if you're using it in that way. For your situation, are you looking for a hands-off global approach like Semian, or something with more control?

If I had a preference, I'd prefer to use a true "Adapter" using delegation and avoid monkey patching (for example a custom wrapper object for `Rails.cache`, but I understand that's a problem for situations where you don't have control over the connection object, like in ActiveRecord. I'm not sure what the right approach is. If you have some examples, or ideas, I'm open to suggestions.

Another issue is that unlike semian, faulty doesn't currently have a host-local storage backend (semian uses sysv). Obviously you wouldn't want to use the redis backend to track circuits for your redis cache, so you'd be using the in-memory backend for those circuits. This means that if you have multiple processes on a single host they won't share circuit state. I haven't yet seriously pursued such a backend yet, but it's theoretically possible since we have swappable circuit storage.

**Comment by justinhoward** [comment]
I thought about it a bit, and I think that the semian approach is probably the most straightforward one here. It seems quite common that ruby libraries and frameworks don't give you access to connection objects directly. Rather, they give you access to a connection config hash. So decorator objects don't end up being very useful. Semian overrides connection object constructors and checks for a semian hash key to configure the circuit. I think we could do the same thing.

```ruby
gem 'faulty', require: %w[faulty faulty/patch/redis]
```

```ruby
# faulty/patch/redis.rb
module Faulty
  module Patch
    def self.circuit_from_hash(name, hash, **options, &block)
      return unless hash

      faulty = hash.delete(:instance)
      # Get a Faulty instance from a constant name if given
      faulty = Kernel.const_get(faulty) if faulty.is_a?(String) || faulty.is_a?(Symbol)
      faulty ||= Faulty
      faulty.circuit(name, **hash, **options, &block)
    end

    module Redis
      def initialize(options = {})
        super
        @faulty_circuit = Patch.circuit_from_hash(:redis, options[:faulty], errors: [Redis::BaseConnectionError])
      end

      def faulty_run
        return yield unless @faulty_circuit
        @faulty_circuit.run { yield }
      end

      def io(&block)
        faulty_run { super }
      end
    end
  end
end

Redis.prepend(Faulty::Patch::Redis)
```

```ruby
# config/application.rb
config.cache_store = :redis_cache_store, {
  url: ENV['REDIS_URL'],
  faulty: {
    instance: Faulty.new,
    name: :rails_cache,
    sample_threshold: 5
  }
}
```

We could even use constants to pass a custom instance from a static config file, for ActiveRecord in Rails:

```yaml
# config/database.yml
production:
  <<: *default
  faulty:
    instance: DB_FAULTY,
    name: main_db
    sample_threshold: 5
```

```ruby
# config/initializers/faulty.rb
DB_FAULTY = Faulty.new(...)
```

Is any of that similar to what you had in mind?

**Comment by senny** [comment]
Hi @justinhoward 

Thanks a lot for the detailed reply. It is inline with what I assumed to be the case from reading the docs. As touched on briefly in my initial question, our situation is quite split. We do have a large amount of 3rd party APIs that we integrate with. The Faulty API works great for that. On the other hand, we are also looking to add circuits to key dependencies like `Rails.cache`, a handful of other Redis instances and some PostgreSQL databases. For those, the Semian approach definitely feels like the right choice (to have complete coverage). When it comes to storage backends, the same applies. For the 3rd party integration points, sharing the circuits across all machines would be handy and given a memory fallback, not too problematic. For our direct dependencies, we would not want to more network dependencies to guard against one of them failing.

I'm currently evaluating which library is better suited for us and am building small proof of concept implementations to get a feel for the problems that surface. That's when I was wondering how faulty encourages wrapping dependencies like `Rails.cache`. I assumed it might not be your primary use-case now. I believe if the gem was to expand into that area as well, using low-level patches (like Semian) is definitely the way to go. While that comes with the usual maintenance challenges of patches, it is also the most effective way to really catch everything without compromise.

Yes, I think the patch based configuration outlined in your last comment is what I was looking for.

**Comment by justinhoward** [comment]
@senny I've opened #14 implementing some of the ideas above for Redis. It seems to work, but I haven't done too much testing yet. If you are able, would you see how it works for your proof-of-concept?

As you mentioned, the question of support is still open. The approach I'm leaning towards is to test only with the edge version of Redis and address issues with prior versions if they come up. As I was writing this, I noticed an issue with Redis 4 in the storage backend anyway, so we now explicitly support 3 and 4, but there's a limit to how many third-party gem versions I'd want to add. It's possible that if the number of patches were to grow, I'd want to split them into separate gems.

**Comment by senny** [comment]
@justinhoward I updated my proof-of-concept with the patches and on first glance, things are working as expected. Note though that I am not able to do any sort of real testing. I did some fiddling in dev mode and tests with Toxiproxy. 

Maybe one follow-up question. We do have a cache instance where we have relied on running the "calculate block" for every request in case the cache is not reachable. I understand that this is most likely not advisable for most uses of a cache but for our situation, it did work well. If I was looking to reproduce said behavior (which is what the `ActiveSupport::Cache` instances do by default), I assume I would write a patch for `AS::Cache` that rescues the circuit error and falls back. Or do you see another approach?

**Comment by justinhoward** [comment]
@senny It appears that in the latest Rails version, ActiveSupport handles the failsafe by rescuing Redis::BaseError.

https://github.com/rails/rails/blob/22f3dfe3cb0b590dd3e80dcb68116dbf2339d789/activesupport/lib/active_support/cache/redis_cache_store.rb#L484

I was wondering if this might be a problem, and it does seem like we're creating a _leaky abstraction_ here. The issue is that any upstream users of Redis clients can expect a certain list of error classes, but we're breaking that assumption. It's possible that the more correct solution to this would be to unwrap the errors in patches so that upstream users will not know the difference. The trade-off with that of course is that there would be no way to tell the difference if for some reason you _did_ need to know. Maybe there is a good way to handle both cases. I'll put some thought into it.

**Comment by senny** [comment]
it's a tricky situation for sure. I would assume that for most use-cases, running the calculate block for 100% of the workload would do nothing else than put pressure on resources one level lower and cause a potential cascading failure. However, it is true that from a user perspective, one would expect that fallback behavior from the Rails cache (since that is how it works by default). Having control over that the exact behavior would certainly be beneficial from a configuration standpoint. Looking through the Semian README reveals that there it might be up to adapters but is recommended to extend the existing exception hierarchy.

> Define exceptions ResourceBusyError and CircuitOpenError. These are raised when the request was rejected early because the resource is out of tickets or because the circuit breaker is open (see Understanding Semian. They should inherit from the base exception class from the raw driver. For example Mysql2::Error or Redis::BaseConnectionError for the MySQL and Redis drivers. This makes it easy to rescue and handle them gracefully in application code, by rescueing the base class.

**Comment by justinhoward** [comment]
@senny As far as I'm concerned, you're right about running the calculate block 100% of the time, but in the Rails documentation, it states "Cache reads and writes never raise exceptions; they just return nil instead, behaving as if there was nothing in the cache".  So that's the decision made by Rails authors, and I don't think it's the responsibility of Faulty to change that behavior.

I guess that raises the question, what do you want your application to do when the cache is offline? Assuming a circuit breaker is in place, your cache will have the best chance it can to recover, but meanwhile, your app needs to either crash when it accesses cache, respond with a fallback, or try to deal with 100% cache misses by shifting load to your primary data store.

I don't know what Shopify does with semian, but [in the patterns section](https://github.com/Shopify/semian#patterns), they advise adding fallbacks on a case-by-case basis or building fallback wrappers. Maybe they also have some automation in place to put the app into a limp mode or try to shift load.

It sounds like we need to return different exception types for each patch. That works for semian's design, but Faulty isn't closely coupled with patches like semian is, so maybe we should give the user options.

```ruby
config.cache_store = :redis_cache_store, {
  url: ENV['REDIS_URL'],
  faulty: {
    patch_errors: true # This would be true by default
  }
}
```

If `patch_errors` is false, patches work exactly like they do in #14 now. If `patch_errors` is true, then we'd raise a `Redis::BaseError` subclass instead.

As far as Rails cache goes, if a user wanted the application to crash for cache circuit errors, they could set `patch_errors` to false, then handle it themselves on a case-by-case basis or with a wrapper. That would seemingly be equivalent to semian.

By the way, I originally misspoke about semian host-local storage. They actually have only per-process in-memory storage for circuits, which maybe you knew already. Thinking about it, the only implementation that makes sense would be to use shared memory, requiring some custom native code, which I don't really want to take on (there is a seemingly abandoned PR for semian doing exactly that). The other way would be to use a daemon process with some kind of IPC but at that point we'd be better off using a local redis server. I might change my mind if there was a gem that made it straightforward to have inter-process shared memory in Ruby.

I'll play around with `patch_errors` and see how that works when get a bit of time.

**Comment by senny** [comment]
I knew that Semian used SysV semaphores to implement their bulk heads and assumed it would use in-process memory based storage for circuits to remove complexity as much as possible.

I think the `patch_errors` flag can offer the best of both worlds. Please do let me know if you update #14 or put up another PR and I will gladly update what I have so far. If I get a chance, I will also try to do the proof of concept soon with Semain to get a better understanding of the choices that have been made and their impact.

As mentioned earlier, we have a huge number of external integration points. Some used frequently, others not so much. Many of them very much not reliable. The added complexity of sharing the circuit storage across all processes for us would actually be a big plus for this goal. I can definitely see us needing the overwrites that Faulty provides (`lock_close!`, ...). If we can get a decent solution to wrap direct dependencies like `Rails.cache` and our other datastores with it, that would be ideal.

Again, thanks for your effort and the thought and time you put into this ticket. It's very much appreciated.

**Comment by justinhoward** [comment]
Hey @senny. I added the `patch_errors` option to the Redis patch. It defaults to `true` as we discussed to provide more-or-less seamless integration by default, so if you update to the latest version it should work as you described where Rails.cache errors are treated as misses.

**Comment by senny** [comment]
Hey @justinhoward, I updated my PoC and I believe generally things are working. However, I was chasing down this very strange error where I would see `Rails.cache.fetch` would still raise `Faulty::CircuitOpenError` even though it should not have given my current configuration. After looking through redis, the rails cache store and faulty to see if options were somehow dropped along the way (we are using a connection pool) I discovered that it must be related to the page code flow that my controller was executing. To visualize, I added a small admin UI that lists circuits and allows to force them open/closed. The controller uses a snippet like so:

```ruby
@circuits = Faulty.list_circuits.map do |name|
  [name, Faulty.circuit(name).status]
end.sort_by(&:first).to_h
```

Now, I suspect the issue is that if I run this before `Rails.cache.fetch` got a chance to define the circuit according to the options that I have set, then the circuit `name` was already defined. I assume because the Redis store still knew that the circuit name `rails-cache` existed. The circuit was then defined with `error_module=Faulty` instead of what's passed when establishing the connection.

Now I wonder, if the idiom from the README is potentially dangerous:

```
statuses = Faulty.list_circuits.map do |name|
  Faulty.circuit(name).status
end
```

Is it possible that on a fresh instance with no circuits in memory, this defined default configurations for circuits that should be more specialized?

**Comment by justinhoward** [comment]
Interesting. I see how that could happen. If I'm understanding correctly, then your admin UI is running in the same process as the rest of your app, so if the admin UI is the first to access the circuit, it will define the circuit with default settings for that process.

Since you're using a connection pool, the circuit won't get defined by the patch until the first time it's used, assuming you don't pre-populate the pool. I guess the fundamental problem here is that circuit options are memoized in-memory, so options and the storage backend can get out-of-sync.

You're right that the status list idiom is wrong, actually in a couple ways. First, because it can define circuits that haven't yet been initialized, and also because the circuit status depends on the options that are set, and if the circuit is not yet initialized, the status could be incorrect.

I think the correct solution might have to be to store key circuit options in the storage backend, and then provide a way to get the status of a circuit without memoizing it.

**Comment by senny** [comment]
> Interesting. I see how that could happen. If I'm understanding correctly, then your admin UI is running in the same process as the rest of your app, so if the admin UI is the first to access the circuit, it will define the circuit with default settings for that process.

Yes, correct. I built a small screen for the PoC to visualize the circuits that used this snippet from the README. I assume this defined circuits with default instead of specific configuration before the regular initialization would run (as I was restarting Puma and loading this page first). Yes, we are using lazy connection pools for Redis so nothing is initialized until the first `Rails.cache.fetch` is run.

**Comment by justinhoward** [comment]
I haven't had much time to work on this last issue. I do think that the best way to solve this is still this:

> I think the correct solution might have to be to store key circuit options in the storage backend, and then provide a way to get the status of a circuit without memoizing it.

However, there is now sort-of a workaround if you are using multiple Faulty instances. If you set `circuit_defaults` in your Faulty instance options, it will apply those defaults to new circuit instances, so in your case, the options would get applied when your admin UI creates them.  I understand this workaround is quite limiting, since you wouldn't be able to configure circuits individually. I still plan to solve the issue when I can.

**Comment by senny** [comment]
Hi @justinhoward

Thanks for the heads up. As you mentioned, using the `circuit_defaults` might be tricky, because we do want specific configurations for a circuit that wraps the cache, than one that wraps a Redis instance that functions as a data store.

No rush tough, realistically, I won't be moving this forward very fast. I still need to implement the PoC with Semian to get a comparison. While faulty ticks most boxes for our use-case. I'm also a bit hesitant to use a brand new library for resilience work 😅. If you happen to have a blog article or similar about your experience building (and using) faulty at work, that would be an interesting read.

**Comment by justinhoward** [comment]
#14 addresses this issue and I've opened #25 to address the problem around listing circuits
