### ISSUE TITLE
Best way to build a global toggle

### ISSUE THREAD

**Issue by senny** [ParentSquare/faulty#35]
Hi @justinhoward,

I've been doing some more testing in our staging environment as well as wrapping a few more of our Redis dependencies with a faulty circuit. I'm getting close to consider running things in production. Heroku didn't really let me cause enough "chaos" in staging to have a solid feeling about my circuit configurations though. Before moving to production, I was thinking to have some kind of global toggle to disable all circuits as a "last resort" safety net. The more we use faulty, the harder it will be to keep a full "revert commit" handy. Our deployment also takes about 20 minutes which would be a significant downtime for us. Do you see an easy possibility where I could implement such a global trigger based on an ENV variable that would affect all circuits in all processes (basically making them a no-op)?

I understand that this is most likely not something that would be part of the gem. I'm ok with doing a monkey patch on my end as well but wanted to hear your thoughts first.

Thanks for your time!

**Comment by justinhoward** [comment]
> implement such a global trigger based on an ENV variable

Since environment variables are only read when a process starts, would that involve restarting your app? In that case, maybe you could simply disable Faulty based on that ENV variable. Currently there's not a way to globally disable Faulty, but that's a feature I've considered. I'm thinking it could be implemented as something like `Faulty::Storage::Disabled`. That would allow configuring the default state to be closed or open.

If you're looking for a way to disable Faulty globally for a running process, that's more difficult. To begin with, it requires some way to signal a running process. I'm not sure how I would approach that.

**Comment by senny** [comment]
yes, we would be restarting. A flag or config option at boot time would be ideal for me.
